#!/usr/bin/env python3
# CPU OC variant generator. Usage: gen_table.py <big_MHz> <little_MHz> > src/oc_targets.h
# Validates the request against the stock-table snapshots below, prints the
# resulting tables to stderr (preview of the in-module retune), and emits the
# baked target header to stdout. Rebuild after generating:
#   make KDIR=/var/tmp/kernel-6.12-2025-09 ARCH=arm64 LLVM=1
#   sh scripts/load-oc.sh [path/to/cpu_oc_mt6789.ko]
# LUT is 12-bit MHz units; targets must be whole MHz and fit.
# Driver ceilings (from vendor .ko decompiles — exceeding what the voters and
# the HW LUT allow just resolves back down; there is nothing to "bypass"):
# - every effective QoS voter must reach the target (module assists touch_boost,
#   mtk_fpsgo_v3, powerhal_cpu_ctrl; see METHOD.md)
# - HW LUT row 0 must be patched to the target (module does it via DT base)
import sys

ABS_CAP = 2700000

# stock snapshots (policy tables read live via diag on MT6789)
STOCK_BIG = [2200000, 2100000, 2000000, 1900000, 1800000, 1700000, 1600000,
             1500000, 1400000, 1300000, 1200000, 1100000, 1000000, 900000,
             800000, 725000]
STOCK_LITTLE = [2000000, 1900000, 1800000, 1700000, 1600000, 1500000, 1450000,
                1400000, 1350000, 1300000, 1250000, 1200000, 1150000, 1100000,
                1050000, 1000000, 950000, 900000, 850000, 800000, 750000,
                700000, 650000, 500000]


def retune(oc, stock):
    """Mirror of retune_table(): uniform shift, minimum anchor kept."""
    delta = oc - stock[0]
    return [f + delta for f in stock[:-1]] + [stock[-1]]


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_table.py <big_MHz> <little_MHz>")
    big, little = int(sys.argv[1]) * 1000, int(sys.argv[2]) * 1000
    for name, oc, stock in (("big", big, STOCK_BIG),
                            ("little", little, STOCK_LITTLE)):
        assert stock[0] < oc <= ABS_CAP, f"{name}: oc {oc} out of range"
        assert oc % 1000 == 0, f"{name}: oc {oc} not whole MHz"
        assert oc // 1000 <= 0xFFF, f"{name}: oc {oc} exceeds 12-bit LUT"
        new = retune(oc, stock)
        assert new[0] == oc and new[-1] == stock[-1], f"{name}: anchor broken"
        assert all(new[i] > new[i + 1] for i in range(len(new) - 1)), \
            f"{name}: not strictly descending"
        gaps = [new[i] - new[i - 1] for i in range(1, len(new))]
        print(f"// {name}: {[f // 1000 for f in new]}", file=sys.stderr)
    guard = max(big - STOCK_BIG[0], little - STOCK_LITTLE[0])
    print(f"// variant big={big // 1000} little={little // 1000} "
          f"guard={guard} | entries {len(STOCK_BIG)}/{len(STOCK_LITTLE)} | OK",
          file=sys.stderr)
    print("/* generated by tools/gen_table.py - do not hand-edit. */")
    print(f"#define PROFILE_BIG_OC {big}")
    print(f"#define PROFILE_LITTLE_OC {little}")
    print(f"#define PROFILE_STEP_GUARD {guard}")


main()
