#!/usr/bin/env python3
# Usage: gen_table.py <big_MHz> <little_MHz> > src/oc_targets.h, then rebuild.
# Whole-MHz targets only (12-bit LUT); validated against stock below.
import sys

ABS_CAP = 2700000

# Stock tables (live diag read, MT6789).
STOCK_BIG = [2200000, 2100000, 2000000, 1900000, 1800000, 1700000, 1600000,
             1500000, 1400000, 1300000, 1200000, 1100000, 1000000, 900000,
             800000, 725000]
STOCK_LITTLE = [2000000, 1900000, 1800000, 1700000, 1600000, 1500000, 1450000,
                1400000, 1350000, 1300000, 1250000, 1200000, 1150000, 1100000,
                1050000, 1000000, 950000, 900000, 850000, 800000, 750000,
                700000, 650000, 500000]


def retune(oc, stock):
    """Mirror of retune_table(): uniform shift, minimum anchor kept."""
    delta = oc - stock[0]
    return [f + delta for f in stock[:-1]] + [stock[-1]]


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_table.py <big_MHz> <little_MHz>")
    big, little = int(sys.argv[1]) * 1000, int(sys.argv[2]) * 1000
    for name, oc, stock in (("big", big, STOCK_BIG),
                            ("little", little, STOCK_LITTLE)):
        assert stock[0] < oc <= ABS_CAP, f"{name}: oc {oc} out of range"
        assert oc % 1000 == 0, f"{name}: oc {oc} not whole MHz"
        assert oc // 1000 <= 0xFFF, f"{name}: oc {oc} exceeds 12-bit LUT"
        new = retune(oc, stock)
        assert new[0] == oc and new[-1] == stock[-1], f"{name}: anchor broken"
        assert all(new[i] > new[i + 1] for i in range(len(new) - 1)), \
            f"{name}: not strictly descending"
        gaps = [new[i] - new[i - 1] for i in range(1, len(new))]
        print(f"// {name}: {[f // 1000 for f in new]}", file=sys.stderr)
    guard = max(big - STOCK_BIG[0], little - STOCK_LITTLE[0])
    print(f"// variant big={big // 1000} little={little // 1000} "
          f"guard={guard} | entries {len(STOCK_BIG)}/{len(STOCK_LITTLE)} | OK",
          file=sys.stderr)
    print("/* generated by tools/gen_table.py - do not hand-edit. */")
    print(f"#define PROFILE_BIG_OC {big}")
    print(f"#define PROFILE_LITTLE_OC {little}")
    print(f"#define PROFILE_STEP_GUARD {guard}")


main()
