/* OC profile: build-time defaults for mt6789-cpu-oc.
 *
 * Edit this file to experiment with your own configuration, then rebuild:
 *
 *   make KDIR=/var/tmp/kernel-6.12-2025-09 ARCH=arm64 LLVM=1
 *   llvm-strip --strip-debug src/cpu_oc_mt6789.ko
 *
 * Precedence at load time: explicit insmod args (or scripts/load-oc.sh env
 * vars, which always pass explicit args) win over the defaults below.
 * For porting to another device/kernel, stock maxima and LUT bases are the
 * values you must change here. See METHOD.md.
 */
#ifndef OC_PROFILE_H
#define OC_PROFILE_H

/* Stock maxima (kHz). Must match the device. */
#define PROFILE_STOCK_BIG_MAX		2200000
#define PROFILE_STOCK_LITTLE_MAX	2000000

/* OC targets (kHz). Generated by tools/gen_table.py into oc_targets.h;
 * the fallback below applies when that file is absent. 0 = skip cluster. */
#if __has_include("oc_targets.h")
#include "oc_targets.h"
#else
#define PROFILE_BIG_OC			2400000
#define PROFILE_LITTLE_OC		2200000
#define PROFILE_STEP_GUARD		200000
#endif

/* MTK cpufreq-hw LUT bases (DT physical). 0 = skip LUT patch. */
#define PROFILE_LUT_PHYS_BIG		0x11bd30UL
#define PROFILE_LUT_PHYS_LITTLE		0x11bc10UL

/* Safety rails (kHz). Targets must satisfy stock < oc <= stock + guard
 * and oc <= abs cap. Guard is generated alongside the targets. */
#define PROFILE_ABS_CAP			2700000

/* Feature defaults (0/1). drop_powerhal=0 leaves powerhal requests intact;
 * set it to 1 only when testing the request-removal workaround. */
#define PROFILE_PATCH_LUT		1
#define PROFILE_HOOK_OVERRIDE		1
#define PROFILE_DROP_POWERHAL		0
#define PROFILE_IGNORE_VERIFY		0

#endif /* OC_PROFILE_H */
